<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
include "../db.php";

if(!isset($_SESSION['user_id']) || $_SESSION['role'] != 'faculty'){
    header("Location: ../login.php");
    exit();
}

$faculty_user_id = $_SESSION['user_id'];

/* get faculty id */
$fac = $conn->query("
SELECT faculty_id FROM faculty WHERE user_id='$faculty_user_id'
")->fetch_assoc();

$faculty_id = $fac['faculty_id'];

/* ================= GET APPROVED STUDENTS ================= */
$students = $conn->query("
SELECT DISTINCT users.id, users.name
FROM applications
JOIN students ON applications.student_id = students.student_id
JOIN users ON students.user_id = users.id
JOIN topics ON applications.topic_id = topics.topic_id
JOIN faculty ON topics.faculty_id = faculty.faculty_id
WHERE faculty.faculty_id='$faculty_id'
AND applications.status='approved'
");

/* ================= SUBMIT REPORT ================= */
if(isset($_POST['submit'])){

    $student_user_id = $_POST['student_id'];
    $feedback = $_POST['feedback'];
    $rating = $_POST['rating'];

    /* get student_id */
    $stu = $conn->query("
    SELECT student_id FROM students WHERE user_id='$student_user_id'
    ")->fetch_assoc();

    $student_id = $stu['student_id'];

    /* insert report */
    $conn->query("
    INSERT INTO reports (student_id, faculty_id, feedback, rating, report_date)
    VALUES ('$student_id','$faculty_id','$feedback','$rating',NOW())
    ");

    /* ================= NOTIFICATION TO STUDENT ================= */
    $conn->query("
    INSERT INTO notifications (user_id, message, type)
    VALUES (
        '$student_user_id',
        'New report generated by your faculty',
        'report'
    )
    ");

    echo "<script>alert('Report submitted successfully');</script>";
}
?>

<!DOCTYPE html>
<html>
<head>
<title>Generate Report</title>

<style>

body{
    font-family:'Segoe UI';
    background:#0f1f1c;
    color:white;
}

.box{
    width:60%;
    margin:50px auto;
    background:white;
    color:black;
    padding:25px;
    border-radius:12px;
}

input,select,textarea{
    width:100%;
    padding:10px;
    margin:10px 0;
}

button{
    background:#2d6a4f;
    color:white;
    padding:10px;
    border:none;
    border-radius:6px;
    cursor:pointer;
}

button:hover{
    background:#40916c;
}

</style>
</head>

<body>

<div class="box">

<h2>Generate Student Report</h2>

<form method="POST">

<label>Select Student</label>
<select name="student_id" required>
<?php while($s=$students->fetch_assoc()){ ?>
<option value="<?php echo $s['id']; ?>">
<?php echo $s['name']; ?>
</option>
<?php } ?>
</select>

<label>Feedback</label>
<textarea name="feedback" required></textarea>

<label>Rating (1 - 5)</label>
<select name="rating" required>
<option value="5">Excellent</option>
<option value="4">Good</option>
<option value="3">Average</option>
<option value="2">Poor</option>
<option value="1">Very Poor</option>
</select>

<button name="submit">Submit Report</button>

</form>

</div>

</body>
</html>